[package]
name = "dawdle-todo-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
dirs = "5.0.1"
lazy-init = "0.5.1"
lazy_static = "1.4.0"
piccolo = "0.3.1"
serde = "1.0.197"
serde_json = "1.0.115"
