import {TitleBar} from "title_bar.slint";
import { VerticalBox } from "std-widgets.slint";

export component MainWindow inherits Window {
    preferred-height: 480px;
    preferred-width: 640px;
    background: whitesmoke;

    background-img := Image{
        width: parent.width;
        height: parent.height;
        source: @image-url("../res/img/banner-main-1.jpg");
        image-fit: cover;
        image-rendering: pixelated;
    }

    VerticalLayout {
        width: parent.width * 95%;
        height: parent.height * 95%;
        spacing: 5px;
        TitleBar {
            vertical-stretch: 2;
        }
        Rectangle {
            background: gray;
            vertical-stretch: 8;
        }
    }
}